### ISSUE TITLE
The skills sections should be similar to Gallup Strenghts

### ISSUE THREAD

**Issue by kd1729** [kd1729/portfolio#61]
Right Now its like this
![image](https://github.com/kd1729/portfolio/assets/55577276/82e73fc8-d844-45fb-b38f-02bbae659606)

Remove the older skills and add these 5 columns keep formatting similar to My gallup strengths
![image](https://github.com/kd1729/portfolio/assets/55577276/fed2425c-e688-418f-8e62-8f5e38d81a20)

**Comment by Soumyaraj321** [comment]
Yess 👍🏻

**Comment by Ryan-Biondo** [comment]
I plan to combine CSS styles for both sections based on the strengths section, and update the HTML to include your new skills. Please let me know if you prefer the squares next to each skill or just the list.

**Comment by kd1729** [comment]
@Ryan-Biondo Thanks for the contribution, merged your PR.
Please don't work on the issues unless not assigned to you, not a good practice.

**Comment by Ryan-Biondo** [comment]
My mistake! I didn't realize it was assigned until after I had worked on it. Thanks for the advice.
