### ISSUE TITLE
Improve the UI/UX, fix bugs, etc

### ISSUE THREAD

**Issue by kd1729** [kd1729/portfolio#64]
Anything that you think can be improved UI/UX. All suggestions are welcome. 

Open an issue and, get it approved than work on that after its assigned to you.

**Comment by sayumimuthu** [comment]
Hi, I'd like to work on this. Can you assign me?

**Comment by kd1729** [comment]
Whatever you want to improve, make an issue regarding that. I will assign you that.

**Comment by Pinaka-Pani-18** [comment]
Can I work on this issue?

**Comment by kd1729** [comment]
> Can I work on this issue?

Yes whatever you fill is missing/can be improved/bugged, please create a separate issue for that and get it assigned by me, and start working on it.
