### ISSUE TITLE
[BUG] The contact form gets submitted even when some fields are empty.

### ISSUE THREAD

**Issue by RuthwikReddy09** [kd1729/portfolio#65]
The contact form gets submitted even when some fields are empty.

<img width="401" alt="Screenshot 2023-10-17 084534" src="https://github.com/kd1729/portfolio/assets/126862059/122f1047-c03e-4448-87a3-13618ff32c23">

I have only entered a name and if I click submit the form gets submitted.

<img width="369" alt="Screenshot 2023-10-17 084735" src="https://github.com/kd1729/portfolio/assets/126862059/63f90585-d3e6-417e-8104-88fa27f50e5b">

Expected Behavior  :
The form should get submitted only when all the fields are filled.

**Comment by RuthwikReddy09** [comment]
I'd like to work on this. Can you assign me?

**Comment by kd1729** [comment]
this was a good one. Thanks for pointing it out. Please go ahead!
