### ISSUE TITLE
Scroll Icon disturbing the scrolling sentence in the main page

### ISSUE THREAD

**Issue by sayumimuthu** [kd1729/portfolio#71]
<img width="718" alt="Screenshot 2023-10-18 at 10 30 15 AM" src="https://github.com/kd1729/portfolio/assets/115540047/809bdb36-a52d-4115-b83b-46ddc141a311">

The icon seems to be in the middle of the final sentence in the main page. Can I adjust it to the bottom so that it doesn't bother the sentence.

**Comment by kd1729** [comment]
Sure

**Comment by AfzalAnsariMd** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by kd1729** [comment]
> Hey, I would like to work on this. Can you please assign this to me?

Hey it's already assigned, you can work on the Adding Blogs Section issue, comment there I will assign you

**Comment by sayumimuthu** [comment]
Hey, made the adjustments and issued a PR
