### ISSUE TITLE
Fix the header hover effect

### ISSUE THREAD

**Issue by kd1729** [kd1729/portfolio#76]
The whole header moves if I hover over any of the header menu item.

**Comment by AfzalAnsariMd** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by suchhanda** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by adv8j** [comment]
Hey! I've sent a PR resolving the same. So can you please review it? Thanks in advance!

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.
