### ISSUE TITLE
Link buttons to your projects

### ISSUE THREAD

**Issue by Petrosdevri** [kd1729/portfolio#81]
I think the title is self-explanatory, it would be useful to add buttons to your projects so that people get easier to them.

**Comment by kd1729** [comment]
@Petrosdevri projects headings are the kind that will direct to that specific project

**Comment by Petrosdevri** [comment]
Yeah, what I said is that we can add buttons below the project description that can head to the links with ease.

**Comment by kd1729** [comment]
> Yeah, what I said is that we can add buttons below the project description that can head to the links with ease.
Yeah great, Do you want to work on this issue?

**Comment by Petrosdevri** [comment]
Sure.
