### ISSUE TITLE
[bug]: Enable Functionality for Mouse Scroll Down Icon Animation

### ISSUE THREAD

**Issue by purnasth** [kd1729/portfolio#90]
# Issue Title: Enable Functionality for Mouse Scroll Down Icon Animation

## Issue Description:
The current mouse animation scroll-down icon on the website is non-functional and purely visual. I propose to implement the necessary functionality to make this animation a useful navigational tool for users.

## Proposed Changes:
- Enable functionality for the mouse scroll-down icon to assist users in navigating down the webpage.

## Attachments
![image](https://github.com/kd1729/portfolio/assets/107195487/2ca0133d-5181-42eb-bc01-9ebadb5de79e)

## Additional Information:
Enabling functionality for the mouse scroll-down icon animation will greatly enhance the user experience by providing a functional navigation aid. Assigning this issue to me will allow me to proceed with implementing this improvement.

Please assign this issue to me for resolution. Thank you for the opportunity to contribute to the website.

**Comment by purnasth** [comment]
Hello @kd1729! I just started working on the project and I found out the HTML code is messed up as html tag is after the head tag and no body tag is there. 
Shall I also fix these as well?

**Comment by kd1729** [comment]
> Hello @kd1729! I just started working on the project and I found out the HTML code is messed up as html tag is after the head tag and no body tag is there. 
> Shall I also fix these as well?

Can you share the screenshot?

**Comment by purnasth** [comment]
![image](https://github.com/kd1729/portfolio/assets/107195487/02e793cc-eb1a-44b6-9ebe-5320f6c96b36)

**Comment by purnasth** [comment]
Oh sorry, this was the problem on the code before I started working with 
![image](https://github.com/kd1729/portfolio/assets/107195487/fe112cf4-d096-4d7e-8752-0ed258a4aa04)
